### ISSUE TITLE
x86 disassembly leads to error.

### ISSUE THREAD

**Issue by ElektroKill** [HoLLy-HaCKeR/dnSpy.Extension.HoLLy#59]
Hello,
when looking at a binary protected with a modified ConfuserEx I noticed that the mod developers have figured out how to cause a crash to occur when disassembling methods.

Steps to reproduce:
1. Download the attached [file.zip](https://github.com/HoLLy-HaCKeR/dnSpy.Extension.HoLLy/files/5797889/file.zip)
2. Go to method at 0x06000046
3. Try to disassemble and see the error.

Thanks in advance!

**Comment by HoLLy-HaCKeR** [comment]
Closing for now as neither of us can reproduce this on master
