### ISSUE TITLE
CFG Blocks can render outside the area dedicated to them

### ISSUE THREAD

**Issue by ElektroKill** [holly-hacker/dnSpy.Extension.HoLLy#65]
When a CFG is created and then dragged it is possible for something like this to happen.
![image](https://user-images.githubusercontent.com/37494960/107850254-4f562380-6e01-11eb-9530-b0ecc49e52f6.png)

**Comment by HoLLy-HaCKeR** [comment]
Most likely a bug within MSAGL itself, since the DockPanel parent of the graph is inside the area.
