### ISSUE TITLE
dnSpyEx release

### ISSUE THREAD

**Issue by Qiangong2** [HoLLy-HaCKeR/dnSpy.Extension.HoLLy#72]
I see that the latest commits mention dnSpyEx support. Are you willing to publish a release? Or is it only built from source at this time?

**Comment by HoLLy-HaCKeR** [comment]
dnSpyEx support works but I hadn't gotten around to publishing the release yet. I'll see if I can do it tomorrow.

**Comment by HoLLy-HaCKeR** [comment]
A new version has been released
