### ISSUE TITLE
Change Display Name menu not found

### ISSUE THREAD

**Issue by chinasmu** [holly-hacker/dnSpy.Extension.HoLLy#77]
I use dnspy6.3
Found the menu SourceMap and it's submenus.
Also found Create CFG, and works fine.
But I cannot find the Change Display Name menu or like this,i do not kown it's accurate name.

**Comment by holly-hacker** [comment]
You should change the decompiler to the sourcemap version and then rightclick a symbol name (such as a method) in the decompiler view. The option should appear there.

**Comment by holly-hacker** [comment]
The decompiler is changed by the dropdown that should say "C#". You should change it to "C# (with sourcemap)".

**Comment by Danon5** [comment]
Thank you. I don't believe this information is available in the readme. It may be obvious to people who are familiar with dnSpy, but—as someone who is new to it, I had no idea how to resolve this issue until asking you directly. If it's not in the readme, maybe it should be there.

**Comment by holly-hacker** [comment]
Updated with ea52dc43b4511e948b210af1bf0a466d13407115.
